import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Marqeue from "@/components/Marqeue";
import { Suspense } from "react";
import Footer from "@/components/Footer";

const HindSiliguri = Hind_Siliguri({

  subsets: ["latin", "bengali"],
  weight: ["300", "400", "500", "600", "700"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${HindSiliguri.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <Suspense fallback={<div>Loading...</div>}>
          <Navbar />
        </Suspense>
        <Suspense fallback={<div>Loading...</div>}>
          <Marqeue />
        </Suspense>
        <main>
          {children}
        </main>
        <Footer></Footer>

      </body>
    </html>
  );
}
